-- 1. Historical Prices Table
create table public.historical_prices (
  id bigint generated by default as identity primary key,
  date date not null unique,
  fnc_price decimal(12,2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.historical_prices enable row level security;

create policy "Public read access for historical prices"
  on public.historical_prices for select
  using ( auth.role() = 'authenticated' );

-- 2. Farmer Profiles Table
create table public.farmer_profiles (
  user_id uuid references auth.users(id) on delete cascade primary key,
  region text,
  hectares decimal(5,2),
  coffee_variety text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.farmer_profiles enable row level security;

create policy "Users can view own profile"
  on public.farmer_profiles for select
  using ( auth.uid() = user_id );

create policy "Users can update own profile"
  on public.farmer_profiles for update
  using ( auth.uid() = user_id );

create policy "Users can insert own profile"
  on public.farmer_profiles for insert
  with check ( auth.uid() = user_id );

-- 3. Sales Notes Table (Simplified for MVP)
create table public.sales_notes (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  date date not null,
  total_amount decimal(12,2) not null,
  kilograms_sold decimal(10,2) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.sales_notes enable row level security;

create policy "Users can view own sales notes"
  on public.sales_notes for select
  using ( auth.uid() = user_id );

create policy "Users can insert own sales notes"
  on public.sales_notes for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own sales notes"
  on public.sales_notes for update
  using ( auth.uid() = user_id );

create policy "Users can delete own sales notes"
  on public.sales_notes for delete
  using ( auth.uid() = user_id );
